[workspace]
members = [
    "packages/brainduck-interpreter",
    "packages/brainduck-web",
    "examples/hello_world",
    "examples/cat",
]

[profile.release]
panic = 'abort' 
codegen-units = 1
opt-level = 'z' 
lto = true