[package]
name = "brainduck-web"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = "0.19"
web-sys = { version = "0.3", features = ["MediaQueryList", "Window", "HtmlTextAreaElement"] }
console_log = { version = "0.2", optional = true }
log = { version = "0.4", optional = true }
brainduck-interpreter = { path = "../brainduck-interpreter" }

[features]
default = ["console_log", "log"]